steps:
- name: 'gcr.io/cel-analysis/bazel:ubuntu_20_0_4'
  entrypoint: bazel
  args:
  - '--output_base=/bazel-test'
  - 'test'
  - '--test_output=errors'
  - '...'
  id: bazel-test
- name: 'gcr.io/cel-analysis/bazel:ubuntu_20_0_4'
  entrypoint: bazel
  args:
  - '--output_base=/bazel-asan'
  - 'test'
  - '--config=asan'
  - '--test_output=errors'
  - '...'
  id: bazel-asan
  waitFor: [ '-' ] # The '-' indicates that this step begins immediately.
- name: 'gcr.io/cel-analysis/bazel:ubuntu_20_0_4'
  entrypoint: bazel
  env:
  - 'CC=gcc'
  - 'CXX=g++'
  args:
  - '--output_base=/bazel-gcc'
  - 'test'
  - '--test_output=errors'
  - '...'
  id: bazel-gcc
  waitFor: [ '-' ] # The '-' indicates that this step begins immediately.
timeout: 1h
options:
  machineType: 'N1_HIGHCPU_8'

