steps:
  - name: 'gcr.io/cloud-marketplace-containers/google/bazel:3.0.0'
    entrypoint: bazel
    args: ['test', '--test_output=errors', '...']
    id: bazel-test
    waitFor: ['-']
    #  - name: 'gcr.io/cloud-marketplace-containers/google/bazel:3.0.0'
    #    entrypoint: bazel
    #    args: ['test', '--config=asan', '--test_output=errors', '...']
    #    id: bazel-asan
    #    waitFor: ['-']

