steps:
- name: 'gcr.io/cel-analysis/bazel:ubuntu_20_0_4'
  entrypoint: bazel
  args: ['test', '--test_output=errors', '...']
  env:
  - 'CC=clang-12'
  - 'CXX=clang++-12'
  id: bazel-test
  waitFor: ['-']
- name: 'gcr.io/cel-analysis/bazel:ubuntu_20_0_4'
  entrypoint: bazel
  args: ['test', '--test_output=errors', '...']
  id: bazel-gcc
  waitFor: ['-']
- name: 'gcr.io/cel-analysis/bazel:ubuntu_20_0_4'
  entrypoint: bazel
  args: ['test', '--config=asan', '--test_output=errors', '...']
  env:
  - 'CC=clang-12'
  - 'CXX=clang++-12'
  id: bazel-asan
  waitFor: ['-']
timeout: 1h
options:
  machineType: 'N1_HIGHCPU_8'
