steps:
- name: 'gcr.io/cel-analysis/bazel:ubuntu_20_0_4'
  entrypoint: bazel
  args:
  - '--output_base=/workspace/.bazel'
  - 'test'
  - '--test_output=errors'
  - '...'
  id: bazel-test
  waitFor: ['-']
- name: 'gcr.io/cel-analysis/bazel:ubuntu_20_0_4'
  entrypoint: bazel
  args:
  - '--output_base=/workspace/.bazel'
  - 'test'
  - '--config=asan'
  - '--test_output=errors'
  - '...'
  id: bazel-asan
  waitFor: ['-']
- name: 'gcr.io/cel-analysis/bazel:ubuntu_20_0_4'
  entrypoint: bazel
  args:
  - '--output_base=/workspace/.bazel'
  - 'test'
  - '--test_output=errors'
  - '...'
  env:
  - CC=gcc
  - CXX=g++
  id: bazel-gcc
  waitFor: ['-']
timeout: 1h
options:
  machineType: 'N1_HIGHCPU_8'
