steps:
- name: 'gcr.io/cel-analysis/gcc-9@sha256:6f2f565b870373a3d33affa3e56748fd296a7322cd421a0b2c0b6c414b6dab5a'
  args:
  - '--output_base=/bazel' # This is mandatory to avoid steps accidently sharing data.
  - 'test'
  - '...'
  - '--noenable_bzlmod'
  - '--copt=-Wno-deprecated-declarations'
  - '--compilation_mode=fastbuild'
  - '--test_output=errors'
  - '--show_timestamps'
  - '--test_tag_filters=-benchmark,-notap'
  - '--jobs=HOST_CPUS*.5'
  - '--local_ram_resources=HOST_RAM*.4'
  id: gcc-9
  waitFor: ['-']
- name: 'gcr.io/cel-analysis/gcc-9@sha256:6f2f565b870373a3d33affa3e56748fd296a7322cd421a0b2c0b6c414b6dab5a'
  env:
  - 'CC=clang-11'
  - 'CXX=clang++-11'
  args:
  - '--output_base=/bazel' # This is mandatory to avoid steps accidently sharing data.
  - 'test'
  - '...'
  - '--noenable_bzlmod'
  - '--copt=-Wno-deprecated-declarations'
  - '--compilation_mode=fastbuild'
  - '--test_output=errors'
  - '--show_timestamps'
  - '--test_tag_filters=-benchmark,-notap'
  - '--jobs=HOST_CPUS*.5'
  - '--local_ram_resources=HOST_RAM*.4'
  id: clang-11
  waitFor: ['-']
timeout: 1h
options:
  machineType: 'E2_HIGHCPU_32'
