steps:
- name: 'gcr.io/cloud-marketplace-containers/google/bazel:3.3.0'
  entrypoint: bazel
  args: ['test', '--test_output=errors', '...']
  id: bazel-test
  waitFor: ['-']
timeout: 1h
options:
  machineType: 'N1_HIGHCPU_8'
